export const CHANGE_ID = 'CHANGE_ID'
export const CHANGE_CONTROL_STATUS = 'CHANGE_CONTROL_STATUS'
export const CHANGE_FILTER = 'CHANGE_FILTER'
export const CHANGE_SONG_TIME = 'CHANGE_SONG_TIME'
export const CHECK_ANIMATION_TIME = 'CHECK_ANIMATION_TIME'

export default {
	CHANGE_ID,
	CHANGE_CONTROL_STATUS,
	CHANGE_FILTER,
	CHANGE_SONG_TIME,
	CHECK_ANIMATION_TIME
}
